/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ACCESS_ENUM2: typeof import('@arco-design/web-vue')['CCESS_ENUM2']
}
